#!/bin/bash

SCRIPTPATH="$( which "$0" )"
SCRIPTPATH="$( readlink --canonicalize "${SCRIPTPATH}" )"
SCRIPTNAME="$( basename "${SCRIPTPATH}" )"
SCRIPTDIR="$( dirname "${SCRIPTPATH}" )"

STDIN=1
STDERR=2

KEYS="$( ssh-add -l )"
if [ $? -gt 0 ] ; then
	printf "%s\n" "${KEYS}" 1>&${STDERR}
	ssh-add
else
	KEYCOUNT="$( printf "%s\n" "${KEYS}" | wc -l )"
	printf "[${SCRIPTNAME}] %d keys already loaded.\n" "${KEYCOUNT}" 1>&${STDERR}
	printf "%s\n" "${KEYS}"
fi
